# Project Info
site_name: 'DevOps Documentation'
site_description: 'Tips and Tricks Documentation'
site_author: 'Mouli Veera'
site_url: 'https://mouliveera.github.io/devopstipsandtricks/'

# Repository Info
repo_name: 'mouliveera/devopstipsandtricks'
repo_url: 'https://github.com/mouliveera/devopstipsandtricks'

# Copyright
copyright: 'Copyright &copy; Mouli veera'

# Context  
nav:
  - Home:
    - 'Index': 'index.md'
  - Elasticsearch:
    - 'How to resolve unassigned shards in Elasticsearch': 'elasticsearch/resolve-unassigned-shards-in-elasticsearch.md'

# Theme and Extension Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
